/*
 * Avalon10 Driver Header - Reconstructed from A1126pro firmware
 * Auto-generated by A1126ProDecompiler
 *
 * Original firmware: CGMiner 4.11.1 for Avalon A1126pro
 * Processor: Kendryte K210 (RISC-V 64-bit)
 */

#ifndef _AVALON10_H_
#define _AVALON10_H_

#include "util.h"
#include "i2c-context.h"

#ifdef USE_AVALON10

/* Frequency Configuration */
#define AVA10_FREQUENCY_MIN      25
#define AVA10_FREQUENCY_MAX      800
#define AVA10_FREQUENCY_STEP     25
#define AVA10_DEFAULT_FREQUENCY  550

/* Voltage Configuration */
#define AVA10_VOLTAGE_LEVEL_MIN  0
#define AVA10_VOLTAGE_LEVEL_MAX  75
#define AVA10_DEFAULT_VOLTAGE_LEVEL 40

/* Temperature Configuration */
#define AVA10_DEFAULT_TEMP_TARGET    90
#define AVA10_DEFAULT_TEMP_OVERHEAT  105

/* Fan Configuration */
#define AVA10_DEFAULT_FAN_MIN    5
#define AVA10_DEFAULT_FAN_MAX    100

/* Polling and Timing */
#define AVA10_DEFAULT_POLLING_DELAY  20  /* ms */

/* Smart Speed Modes */
#define AVA10_SMARTSPEED_OFF     0
#define AVA10_SMARTSPEED_MODE1   1
#define AVA10_DEFAULT_SMART_SPEED AVA10_SMARTSPEED_MODE1

/* Hash Chain Configuration */
#define AVA10_DEFAULT_MINER_CNT  4
#define AVA10_DEFAULT_ASIC_MAX   26
#define AVA10_DEFAULT_PLL_CNT    4

/* Protocol Definitions (from avalon8 pattern) */
#define AVA10_MM_VER_LEN    15
#define AVA10_MM_DNA_LEN    8
#define AVA10_H1            'C'
#define AVA10_H2            'N'

/* Packet Types */
#define AVA10_P_DETECT      0x10
#define AVA10_P_STATIC      0x11
#define AVA10_P_JOB_ID      0x12
#define AVA10_P_COINBASE    0x13
#define AVA10_P_MERKLES     0x14
#define AVA10_P_HEADER      0x15
#define AVA10_P_TARGET      0x16
#define AVA10_P_JOB_FIN     0x17

#define AVA10_P_SET         0x20
#define AVA10_P_SET_FIN     0x21
#define AVA10_P_SET_VOLT    0x22
#define AVA10_P_SET_PLL     0x25
#define AVA10_P_SET_SS      0x26

#define AVA10_P_POLLING     0x30
#define AVA10_P_NONCE       0x42
#define AVA10_P_STATUS      0x41

/* Command Line Options (extracted from firmware) */
// --avalon10-core-clk-sel
// --avalon10-dh-high
// --avalon10-dh-low
// --avalon10-fan-spd
// --avalon10-freq
// --avalon10-freq-high
// --avalon10-freq-low
// --avalon10-freq-sel
// --avalon10-h2ltime0-spd
// --avalon10-hash-od
// --avalon10-lv1-th-ms
// --avalon10-lv1-th-msadd
// --avalon10-lv2-th-ms
// --avalon10-lv2-th-msadd
// --avalon10-lv3-th-ms
// --avalon10-lv3-th-msadd
// --avalon10-lv4-th-ms
// --avalon10-lv4-th-msadd
// --avalon10-mux-h2l
// --avalon10-mux-l2h

/* Function Declarations */
extern void avalon10_init(struct cgpu_info *avalon10);
extern int64_t avalon10_scanhash(struct thr_info *thr);
extern void avalon10_statline_before(char *buf, size_t bufsiz, struct cgpu_info *avalon10);
extern struct api_data *avalon10_api_stats(struct cgpu_info *avalon10);

#endif /* USE_AVALON10 */
#endif /* _AVALON10_H_ */
