; Avalon A1126pro K210 Firmware Disassembly
; Generated by RISC-V Disassembler
; Base address: 0x80000000 (SRAM)
; Architecture: RISC-V 64-bit with C extension
;
; Memory Map:
;   0x00000000 - 0x00FFFFFF : SPI Flash
;   0x80000000 - 0x805FFFFF : SRAM (6MB)
;   0x40000000 - 0x4FFFFFFF : Peripherals
;
======================================================================

; BOOT SECTION (0x00000000 - 0x00001000)
;---------------------------------------------------------------------

  80000000:	db00                	sw	s0,48(a4)
  80000002:	00b9                	addi	ra,ra,14
  80000004:	2100                	fld	fs0,0(a0)
  80000006:	eda8                	sd	a0,88(a1)
  80000008:	cefe                	sw	t6,92(sp)
  8000000a:	01fa                	slli	gp,gp,0x1e
  8000000c:	0100                	addi	s0,sp,128
  8000001a:	0000                	unimp
  8000001c:	7300                	ld	s0,32(a4)
  8000001e:	3050                	fld	fa2,160(s0)
  80000020:	7330                	ld	a2,96(a4)
  80000022:	2050                	fld	fa2,128(s0)
  80000024:	7330                	ld	a2,96(a4)
  80000026:	4050                	lw	a2,4(s0)
  80000028:	7330                	ld	a2,96(a4)
  8000002a:	4050                	lw	a2,4(s0)
  8000002c:	9734                	.insn	2, 0x9734
  8000002e:	0002                	c.slli64	zero
  80000030:	9300                	.insn	2, 0x9300
  80000032:	0282                	c.slli64	t0
  80000034:	7310                	ld	a2,32(a4)
  80000036:	5290                	lw	a2,32(a3)
  80000038:	8130                	.insn	2, 0x8130
  8000003a:	0140                	addi	s0,sp,132
  8000003c:	8141                	srli	a0,a0,0x10
  8000003e:	0141                	addi	sp,sp,16
  80000040:	8142                	mv	sp,a6
  80000042:	0142                	slli	sp,sp,0x10
  80000044:	01438143          	fmadd.s	ft2,ft7,fs4,ft0,rne
  80000048:	8144                	.insn	2, 0x8144
  8000004a:	0144                	addi	s1,sp,132
  8000004c:	8145                	srli	a0,a0,0x11
  8000004e:	0145                	addi	sp,sp,17
  80000050:	8146                	mv	sp,a7
  80000052:	0146                	slli	sp,sp,0x11
  80000054:	01478147          	fmsub.s	ft2,fa5,fs4,ft0,rne
  80000058:	8148                	.insn	2, 0x8148
  8000005a:	0148                	addi	a0,sp,132
  8000005c:	8149                	srli	a0,a0,0x12
  8000005e:	0149                	addi	sp,sp,18
  80000060:	814a                	mv	sp,s2
  80000062:	014a                	slli	sp,sp,0x12
  80000064:	014b814b          	fnmsub.s	ft2,fs7,fs4,ft0,rne
  80000068:	814c                	.insn	2, 0x814c
  8000006a:	014c                	addi	a1,sp,132
  8000006c:	814d                	srli	a0,a0,0x13
  8000006e:	014d                	addi	sp,sp,19
  80000070:	814e                	mv	sp,s3
  80000072:	014e                	slli	sp,sp,0x13
  80000074:	994f814f          	fnmadd.s	ft2,ft11,fs4,fs3,rne
  80000078:	7362                	ld	t1,56(sp)
  8000007a:	02a0                	addi	s0,sp,328
  8000007c:	7330                	ld	a2,96(a4)
  8000007e:	3010                	fld	fa2,32(s0)
  80000080:	5300                	lw	s0,32(a4)
  80000082:	0000                	unimp
  80000084:	d3f2                	sw	t3,228(sp)
  80000086:	0000                	unimp
  80000088:	53f2                	lw	t2,60(sp)
  8000008a:	0001                	nop
  8000008c:	d3f2                	sw	t3,228(sp)
  8000008e:	0001                	nop
  80000090:	53f2                	lw	t2,60(sp)
  80000092:	0002                	c.slli64	zero
  80000094:	d3f2                	sw	t3,228(sp)
  80000096:	0002                	c.slli64	zero
  80000098:	53f2                	lw	t2,60(sp)
  8000009a:	d3f20003          	lb	zero,-705(tp) # 0xfffffffffffffd3f
  8000009e:	53f20003          	lb	zero,1343(tp) # 0x53f
  800000a2:	0004                	.insn	2, 0x0004
  800000a4:	d3f2                	sw	t3,228(sp)
  800000a6:	0004                	.insn	2, 0x0004
  800000a8:	53f2                	lw	t2,60(sp)
  800000aa:	0005                	c.nop	1
  800000ac:	d3f2                	sw	t3,228(sp)
  800000ae:	0005                	c.nop	1
  800000b0:	53f2                	lw	t2,60(sp)
  800000b2:	0006                	c.slli	zero,0x1
  800000b4:	d3f2                	sw	t3,228(sp)
  800000b6:	0006                	c.slli	zero,0x1
  800000b8:	53f2                	lw	t2,60(sp)
  800000ba:	d3f20007          	.insn	4, 0xd3f20007
  800000be:	53f20007          	.insn	4, 0x53f20007
  800000c2:	0008                	.insn	2, 0x0008
  800000c4:	d3f2                	sw	t3,228(sp)
  800000c6:	0008                	.insn	2, 0x0008
  800000c8:	53f2                	lw	t2,60(sp)
  800000ca:	0009                	c.nop	2
  800000cc:	d3f2                	sw	t3,228(sp)
  800000ce:	0009                	c.nop	2
  800000d0:	53f2                	lw	t2,60(sp)
  800000d2:	000a                	c.slli	zero,0x2
  800000d4:	d3f2                	sw	t3,228(sp)
  800000d6:	000a                	c.slli	zero,0x2
  800000d8:	53f2                	lw	t2,60(sp)
  800000da:	d3f2000b          	.insn	4, 0xd3f2000b
  800000de:	53f2000b          	.insn	4, 0x53f2000b
  800000e2:	000c                	.insn	2, 0x000c
  800000e4:	d3f2                	sw	t3,228(sp)
  800000e6:	000c                	.insn	2, 0x000c


; FUNCTIONS
;---------------------------------------------------------------------

